### PR TITLE
Update to v1.10.0

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
Closes #7, #8, #9, #10

**Comment by synapticarbors** [comment]
@deeplook - I'm updating the `backoff` feedstock in this PR

**Comment by deeplook** [comment]
@synapticarbors Thanks a ton!

**Comment by synapticarbors** [comment]
closes #7, closes #8, closes #9, closes #10

**Pull request merged**
